//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBrainzArtistSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identifier
    {
        public int id { get; set; }
        public int artistid { get; set; }
        public string uniqueid { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
