//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBrainzArtistSearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicBrainzDBEntities : DbContext
    {
        public MusicBrainzDBEntities()
            : base("name=MusicBrainzDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alias> Aliases { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Identifier> Identifiers { get; set; }
    }
}
